### PR TITLE
chore: add osp configuration

### PR DESCRIPTION
**Pull request by Phil91**
## Description

Add configuration for the osp callback

## Why

To be able to do the callback to the osp a technical user is needed for authentication.

## Issue

N/A - Jira Issue: CPLP-2638

## Depending Backend PR

[#260](https://github.com/eclipse-tractusx/portal-backend/pull/260)

## Checklist

- [x] I have performed a self-review of my changes
- [x] I have successfully tested my changes
- [x] I have added comments in the default values.yaml file with helm-docs syntax ('# -- ') if relevant for installation
- [x] I have commented my changes, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by Phil91** [comment]
Before merging this, we need to set the clientId and secret for the technical user in the vault for all environments. need to clarify with @jjeroch  which roles the technical user needs

**Review by evegufy — CHANGES_REQUESTED** [review]
Looks good! Could please update the comment here as well? https://github.com/eclipse-tractusx/portal-cd/blob/0fd33b052c6d7190e7bbcf88dd970a226e58e2b6/charts/portal/values.yaml#L242C121-L242C121

**Comment by Phil91** [comment]
> Looks good! Could please update the comment here as well? https://github.com/eclipse-tractusx/portal-cd/blob/0fd33b052c6d7190e7bbcf88dd970a226e58e2b6/charts/portal/values.yaml#L242C121-L242C121

Done :)

**Review by evegufy — APPROVED** [review]

**Comment by Phil91** [comment]
@evegufy since we changed the process logic from setting up a technical user for the osps to the osps setting the auth data in the portal, the config has changed

**Review by evegufy — APPROVED** [review]

**Pull request merged**
